name: C/C++ CI

on:
  push:
    branches: [ refactor ]
  pull_request:
    branches: [ refactor ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: install_prereq
      run: pip3 install setuptools wheel
    - name: install_conan
      run: pip3 install conan
    - name: configure
      run: cmake -B build
    - name: make
      run: cmake --build build
